site_name: fusionpipe
theme:
  name: material
  features:
    - content.code.copy

nav:
  - Getting Started: intro.md
  - Installation:
      - Single User (bare metal): installation_single.md
      - Multiple Users (bare metal): dev_maintainer_guide.md
  - User Guide:
      - Develop a Node (Basics): user_guide/develop_node.md
      - Pipeline Interaction:
          - Basic Interaction: user_guide/pipeline_interaction.md
          - Advanced Interaction: user_guide/pipeline_interaction_advanced.md
          - Full list of commands: user_guide/complete_list_interaction.md
      - External Dependencies:
          - python: package_management_python.md
          - matlab: package_management_matlab.md
      - Best practices:
          - Develop your pipeline together with your custom package: best_practices_pipeline_package.md
          - VSCode best practice developing a node: best_practices_vscode.md

plugins:
  - search
  - mkdocstrings


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  