site_name: fusionpipe
theme:
  name: material

nav:
  - Getting Started: intro.md
  - Installation:
      - Single User (bare metal): installation_single.md
      - Multiple Users (bare metal): dev_maintainer_guide.md
  - User Guide:
      - Develop a Node: user_guide/develop_node.md
      - Pipeline Interaction: pipeline_interation.md


plugins:
  - search
  - mkdocstrings