site_name: fusionpipe
site_url: https://fusionpipe.github.io/fusionpipe/
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: intro.md
  - Installation:
      - Single User (Bare metal): installation_single.md
      - Multiple Users (Bare metal): dev_maintainer_guide.md
  - User Guide:
      - Develop a Node (Basics): user_guide/develop_node.md
      - Pipeline Interaction:
          - Basic Interaction: user_guide/pipeline_interaction.md
          - Advanced Interaction: user_guide/pipeline_interaction_advanced.md
          - Full list of commands: user_guide/complete_list_interaction.md
      - External Dependencies:
          - python: package_management_python.md
          - matlab: package_management_matlab.md
      - Best practices:
          - Develop your pipeline together with your custom package: best_practices_pipeline_package.md
          - Develop with VSCode: best_practices_vscode.md
          - Develop with Jupyter Notebooks in VSCode: best_practices_jupyter_vscode.md
          - Develop with Jupyter Lab: best_practices_jupyter_lab.md
          - Develop with Matlab: best_practices_matlab.md
          - Develop with Octave: best_practices_octave.md
  - Developer Guide:
      - Design Principles: developer_guide/design_principles.md


plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  version:
    method: material