site_name: fusionpipe
theme:
  name: material

nav:
  - Getting Started: intro.md
  - User Guide:
      - Develop a Node: user_guide/develop_node.md
  - Developer/Maintainer Guide: dev_maintainer_guide.md


plugins:
  - search
  - mkdocstrings